name: Deploy 
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Install dependencies
      - name: Install Dependencies
        run: npm install
      
      # Build the project
      - name: Run build
        run: npm run build
      
      # Setup SSH
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SECRET_SSH_KEY }}

      # Update known_hosts
      - name: Update known_hosts
        run: ssh-keyscan -H 51.178.27.150 >> ~/.ssh/known_hosts
    
      # Copy build files to the remote server
      - name: Copy build files
        run: scp -r dist/* debian@51.178.27.150:/var/www/html/PokemonDex
