name: GitHub Actions Demo
on: [push]
jobs:
  PokemonAction:
    runs-on: ubuntu-latest
    steps:
      # Un simple "Hello world" pour commencer
      - name: Hello world
        run: "echo Hello, world!"

      # On fait un checkout du code depuis le dépôt
      - name: GitHub Checkout
        uses: actions/checkout@v2

      # On installe Node.js avec un cache pour npm
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json

      #  On installe les dépendances et on nettoie node_modules
      - name: Install Dependencies
        run: npm ci
      
      # On lance les vérifications de type TypeScript
      - name: Run TypeScript type-check
        run: npx tsc -b --noEmit

      # On build le projet
      - name: Run build
        run: npm run build

      # On vérifie le formatage avec Prettier ( tabulation, espaces, etc.)
      - name: run prettier
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}"
      
      # On vérifie les erreurs de code avec ESLint (qualité du code)
      - name: run eslint
        run: npx eslint "src/**/*.{js,jsx,ts,tsx}"

      # On lance le serveur 
      - name: Start the development server
        run: npm run dev &

      # On attend que l'application soit prête
      - name: Wait for app to be ready
        run: npx wait-on http://localhost:5173

      # On lance les tests Cypress sur Chrome
      - name: E2E on Chrome
        uses: actions/checkout@v4
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome
      
      # On upload les vidéos des tests Cypress
      - name: Upload Cypress Video Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cypress-video
          path: cypress/videos

      #setup SSH
      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: |
                  ${{ secrets.SECRET_SSH_KEY }}

      # Update known_hosts
      - name: Update known_hosts
        run: ssh-keyscan -H 51.178.27.150 >> ~/.ssh/known_hosts
    
      - name: ls -la
        run: ssh ls -la /var/www/html