name: GitHub Actions Demo
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: "echo Hello, world!"

      - name: GitHub Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci
      
      - name: Run TypeScript type-check
        run: npx tsc --noEmit

      - name: Run build
        run: npm run build

      - name: run prettier
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}"

      - name: run eslint
        run: npx eslint "src/**/*.{js,jsx,ts,tsx}"
