name: GitHub Actions Demo
on: [push]
jobs:
  PokemonAction:
    runs-on: ubuntu-latest
    steps:
      # Un simple "Hello world" pour commencer
      - name: Hello world
        run: "echo Hello, world!"

      # On fait un checkout du code depuis le dépôt
      - name: GitHub Checkout
        uses: actions/checkout@v2

      # On installe Node.js avec un cache pour npm
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json

      #  On installe les dépendances et on nettoie node_modules
      - name: Install Dependencies
        run: npm ci
      
      # On lance les vérifications de type TypeScript
      - name: Run TypeScript type-check
        run: npx tsc -b --noEmit

      # On build le projet
      - name: Run build
        run: npm run build

      # On vérifie le formatage avec Prettier ( tabulation, espaces, etc.)
      - name: run prettier
        run: npx prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,scss,md}"
      
      # On vérifie les erreurs de code avec ESLint
      - name: run eslint
        run: npx eslint "src/**/*.{js,jsx,ts,tsx}"
 